<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_GeneralAppearanceNotificationsPreferenc_bc2e8e</name>
   <tag></tag>
   <elementGuidId>0a1cece7-c9bd-4385-81f3-0b0a676d080f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mx_Dialog_StaticContainer']/div/div/div[3]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mx_TabbedView.mx_TabbedView_tabsOnLeft</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx_TabbedView mx_TabbedView_tabsOnLeft</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GeneralAppearanceNotificationsPreferencesVoice &amp; VideoSecurity &amp; PrivacyHelp &amp; AboutGeneralProfileDisplay Name@nctai:matrix.orgUploadCancelSaveAccountSet a new account password...Current passwordNew PasswordConfirm passwordChange PasswordEmail addressesEmail AddressAddPhone numbers🇬🇧+44Phone NumberAddLanguage and regionEnglish (US) DiscoveryEmail addressesDiscovery options will appear once you have added an email above.Phone numbersDiscovery options will appear once you have added a phone number above.Identity server (vector.im)You are currently using vector.im to discover and be discoverable by existing contacts you know. You can change your identity server below.Enter a new identity serverChangeDisconnecting from your identity server will mean you won't be discoverable by other users and you won't be able to invite others by email or phone.DisconnectManage integrations(scalar.vector.im)Use an integration manager (scalar.vector.im) to manage bots, widgets, and sticker packs.Integration managers receive configuration data, and can modify widgets, send room invites, and set power levels on your behalf.Deactivate accountAccount managementDeactivating your account is a permanent action - be careful!Deactivate Account</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mx_Dialog_StaticContainer&quot;)/div[@class=&quot;mx_Dialog_wrapper mx_Dialog_staticWrapper&quot;]/div[@class=&quot;mx_Dialog&quot;]/div[@class=&quot;mx_UserSettingsDialog mx_Dialog_fixedWidth&quot;]/div[@class=&quot;mx_SettingsDialog_content&quot;]/div[@class=&quot;mx_TabbedView mx_TabbedView_tabsOnLeft&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mx_Dialog_StaticContainer']/div/div/div[3]/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a Group Chat'])[1]/following::div[18]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[3]/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
